### ISSUE TITLE
failed to clone the datasets due to exceeding data quota

### ISSUE THREAD

**Issue by abrosua** [shengzesnail/PIV_dataset#1]
Cloning the repo returns an error due to the exceeding data quota for the image datasets, as shown by the following:
> Error downloading object: PIV-genImages/data/DNS_turbulence.zip (0fe605a): Smudge error: Error downloading PIV-genImages/data/DNS_turbulence.zip (0fe605a3fe095896396cf03a49c259f7c4909d7900f497ff708b460c7ddbeabf): batch response: This repository is over its data quota. Purchase more data packs to restore access.

However, obtaining the datasets via baidu cloud is quite difficult since I got troubles creating the account from overseas.

Could you help me or give me some suggestions to handle this problem in order to obtain the images datasets? Thank you very much for your attention.

Regards

**Comment by shengzesnail** [comment]
Hi abrosua, thank you for your attention. I am sorry that you couldn't access to the data and I will find a better way to share these large files. At this moment, please try to download the data from the following links:

https://drive.google.com/drive/folders/1wP2kkeX4M7nCAsSIi52yMpO96RiT4NXq?usp=sharing
https://drive.google.com/drive/folders/1uJIHonOZGfhWtZcR-F0aGH7tnbLbCFn0?usp=sharing

Please let me know if they work or not. 
Best,

**Comment by Dang123** [comment]
I work very well. Thanks for your help.

**Comment by abrosua** [comment]
> Hi abrosua, thank you for your attention. I am sorry that you couldn't access to the data and I will find a better way to share these large files. At this moment, please try to download the data from the following links:
> 
> https://drive.google.com/drive/folders/1wP2kkeX4M7nCAsSIi52yMpO96RiT4NXq?usp=sharing
> https://drive.google.com/drive/folders/1uJIHonOZGfhWtZcR-F0aGH7tnbLbCFn0?usp=sharing
> 
> Please let me know if they work or not.
> Best,

It works for me! Thank you very much for your reply.
