### ISSUE TITLE
Data zip files are empty.

### ISSUE THREAD

**Issue by DaikiKurihara** [shengzesnail/PIV_dataset#3]
I'm trying to clone this repository and it was successful. However, the zip files which actually have data in are empty zip files. I also tried to download files directly but the results were the same.

**Comment by shengzesnail** [comment]
Hi,

Sorry about that. Cloning these big files is a trouble. 
You can download the data from Google Drive links. Please see the issue #1 

Thanks!
Best

**Comment by DaikiKurihara** [comment]
Hi,

Thank you very much. I could download the files from the issue #1.
