### ISSUE TITLE
Load data problem class II

### ISSUE THREAD

**Issue by esgomezm** [shengzesnail/PIV_dataset#4]
Hi,

Congratulations for the impressive work! I really enjoy reading it. 

I would like to test the proposed approach on my own data. It was ok to download the data from problem class I, but could you please guide me a bit into how to uncompress&open the data in zenodo (https://zenodo.org/record/4432496#.YZ1jsfHP06E)? All the files are tfrecord and I don't know how to extract the optical flow and input data information from it. 

Thank you!

**Comment by shengzesnail** [comment]
Hi,

Thanks for reaching out.

However, the Problem Class II is modified based on Class I (this repo) by Lagemann et al. 2021, who used tfrecord to compress the data. Please check 'tf.data.TFRecordDataset' for more information. Thanks. 

Best,
